name: Main Workflow
on: [push, pull_request_target]

jobs:
  build:
    name: Build APK for Android
    runs-on: macos-latest
    
    steps:
    - name: Clone repo
      uses: actions/checkout@v2
    
    - name: Install Java
      uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # or: 'dev' or 'beta'
          
    - name: Decode Google Services
      env:
        FIREBASE_ANDROID: ${{ secrets.FIREBASE_ANDROID }}
      run: |
        touch android/app/google-services.json
        echo $FIREBASE_ANDROID > android/app/google-services.json
      
    - name: Build APK
      run: |
        flutter pub get
        flutter build apk

#     - name: Test
#       run: flutter test test/widget_test.dart
